spring.application.name=syncboard
spring.datasource.url=jdbc:postgresql://66.116.206.132:5475/syncboard_db
spring.datasource.username=syncboard_admin
spring.datasource.password=YourNewSecurePassword123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
server.port=${PORT:8092}